### ISSUE TITLE
New Release / Terser

### ISSUE THREAD

**Issue by hammockvienna** [udovicic/magepack-docker#2]
Hi

there is a new important bugfix in magepack. Could someone create a new docker image?
https://github.com/magesuite/magepack/issues/155
This would be awesome :-)

**Comment by udovicic** [comment]
Hi @hammockvienna ,

Thanks, for the report, and sorry for waiting, somehow I missed this issue.

A new release has been made with version 2.11.2:
* [git tag](https://github.com/udovicic/magepack-docker/releases/tag/2.11.2)
* [docker image tag](https://hub.docker.com/layers/udovicic/magepack/2.11.2/images/sha256-0674b472723863e54964f3ac722905659b8cb3b62f85a11e88f978edb5a63de3?context=repo)

This includes the fix you have mentioned above.
