### ISSUE TITLE
Missing libXss.so.1

### ISSUE THREAD

**Issue by cmorbitzer** [udovicic/magepack-docker#4]
When running `magepack generate` in the container after building, I get the following error: `/usr/local/lib/node_modules/magepack/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory`

Per these instructions: https://askubuntu.com/questions/547151/error-while-loading-shared-libraries-libxss-so-1
I was able to fix this by installing `libxss1` in the container:
```
docker run --rm -it --entrypoint bash udovicic/magepack:2.11
apt-get update
apt-get install libxss1
```

I'm not familiar enough with Docker to submit a PR. Opening this issue to let you know. Thanks!

**Comment by udovicic** [comment]
Thanks to @fanglingsu this one has been resolved. A new image has been pushed to [dockerhub](https://hub.docker.com/layers/udovicic/magepack/2.11.2/images/sha256-b0d8fbae16ccc2631c15e7073252e362ae222e40b225bada403db82ca9853f29?context=explore).
